// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {service} from '../models';
import {typeless} from '../models';

export function AddDictionaryTerm(arg1:string):Promise<void>;

export function ClearDictionary():Promise<number>;

export function CopyText(arg1:string):Promise<void>;

export function DeleteDictionaryWord(arg1:string):Promise<void>;

export function GetConfig():Promise<service.Config>;

export function ImportDictionaryFile(arg1:string,arg2:number,arg3:boolean):Promise<typeless.ImportResult>;

export function ListDictionaryWords():Promise<Array<typeless.DictionaryWord>>;

export function QueryHistory(arg1:service.HistoryQuery):Promise<Array<typeless.TranscriptRecord>>;

export function ResetDictionary(arg1:string,arg2:number):Promise<typeless.ResetResult>;

export function SelectTextFile():Promise<string>;

export function SetConfig(arg1:service.Config):Promise<void>;
