// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDictionaryTerm(arg1) {
  return window['go']['main']['App']['AddDictionaryTerm'](arg1);
}

export function ClearDictionary() {
  return window['go']['main']['App']['ClearDictionary']();
}

export function CopyText(arg1) {
  return window['go']['main']['App']['CopyText'](arg1);
}

export function DeleteDictionaryWord(arg1) {
  return window['go']['main']['App']['DeleteDictionaryWord'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function ImportDictionaryFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['ImportDictionaryFile'](arg1, arg2, arg3);
}

export function ListDictionaryWords() {
  return window['go']['main']['App']['ListDictionaryWords']();
}

export function QueryHistory(arg1) {
  return window['go']['main']['App']['QueryHistory'](arg1);
}

export function ResetDictionary(arg1, arg2) {
  return window['go']['main']['App']['ResetDictionary'](arg1, arg2);
}

export function SelectTextFile() {
  return window['go']['main']['App']['SelectTextFile']();
}

export function SetConfig(arg1) {
  return window['go']['main']['App']['SetConfig'](arg1);
}
